name: Deploy MultiDocker
on:
  push:
    branches:
      - main # change to 'master' if your default branch is master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Log in to Docker Hub using your secrets
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Test build for client
      - name: Build and test client
        run: |
          docker build -t ${DOCKER_USERNAME}/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true ${DOCKER_USERNAME}/react-test npm test

      # Build all production images with your Docker Hub username
      - name: Build production images
        run: |
          docker build -t ${DOCKER_USERNAME}/multi-client ./client
          docker build -t ${DOCKER_USERNAME}/multi-nginx ./nginx
          docker build -t ${DOCKER_USERNAME}/multi-server ./server
          docker build -t ${DOCKER_USERNAME}/multi-worker ./worker

      # Push images to your Docker Hub account
      - name: Push images
        run: |
          docker push ${DOCKER_USERNAME}/multi-client
          docker push ${DOCKER_USERNAME}/multi-nginx
          docker push ${DOCKER_USERNAME}/multi-server
          docker push ${DOCKER_USERNAME}/multi-worker
