name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and test client
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test

      - name: Build production images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client ./client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx ./nginx
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-server ./server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-client
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-server
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-518890434707
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
